services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d mydb"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./backend:/app
      - /app/node_modules:/app/node_modules
    command: >
      sh -c "
        echo 'Waiting for database to be ready...' &&
        npx prisma db push --accept-data-loss &&
        npx prisma generate &&
        npm run seed &&
        npx ts-node index.ts
      "

  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3001:3000"
  #   volumes:
  #     - ./frontend:/app
  #     - /app/node_modules:/app/node_modules
  #   depends_on:
  #     - backend
  #   command: sh -c "npm run dev"

volumes:
  postgres_data:
